# Generated by Django 4.1.7 on 2023-02-17 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 17, 21, 38, 46, 147204)),
        ),
    ]
