# Generated by Django 4.1.7 on 2023-02-21 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_todo_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 21, 20, 20, 25, 38695)),
        ),
    ]
